[variables]
;==============================================
;== Change Values to match your system specs ==
;==============================================
;Set GPU Memory Total In MB
GPUMem=11264

;Set Max Download Speed In Mbps (Advertised Internet Speed if unknown go to speetest.net)
SpeedD=30

;Set Max Upload Speed In Mbps (Advertised Internet Speed if unknown go to speetest.net)
SpeedU=4.5

;CPU Min and Max Fan Speeds in RPM
CPUFanMin=2050
CPUFanMax=3000

;Speed Fan CPU Temp Line - Found in SpeedFan >> Configure >> Temperatures >> CPU
SFCPUTemp=1

;Speed Fan CPU Fan Line - Found in SpeedFan >> Configure >> Fans >> CPU Fan
SFCPUFan=1

;Speed Fan GPU 1 Number - Found in SpeedFan >> Configure >> Temperatures >> GPU
SFGPU1=0

;Speed Fan GPU 2 Number (Ignore Possibility for Multi-GPU Eventually)
SFGPU2=1

;Set drives to monitor
Drive1=C:
Drive2=D:
Drive3=E:
Drive4=F:

;Set Averages
AVERAGE1=30
AVERAGE2=120

;GDI Monitor Process
GDIProcess1="Rainmeter.exe"

;===================================================================
;====== IGNORE BELOW THIS LINE UNLESS YOU KNOW WHAT THESE ARE ======
;===================================================================
;Network Settings
;Set your network interface number.
Interface=0

;Connections
;Enable / Disable Number of Connections [ Disable 1 / Enable 0 ]
Connections=0
