[variables]
;==================================================================
;Font and Color Settings
;==================================================================

;----------------------------------------------------
;Font 1 Settings
;----------------------------------------------------

Font1Name=Tahoma

;---------------------------- Antialias Enable / Diable

;AntiAlias [ Disable 0 / Enable 1 ]
AA=0
;----------------------------------------------------
;Color Settings
;----------------------------------------------------
;Dark Grey
color1=20, 20, 20, 255

;Blue
color2=0, 100, 200, 255

;Blue Dark
Color3=0, 50, 100, 100

;Green
color4=0, 200, 0, 200

;Green Dark
color5=0, 200, 0, 100

;Title Bar Outline
color6=50, 50, 50, 255

;Message Body
color7=0, 0, 0, 255

;Bar_Red
color8=200,0,0,200

;Bar_Orange
color9=250,125,0,200

;Font 1
font1=255, 255, 255, 200

;==================================================================
;CPU, RAM, GPU Settings
;==================================================================

;CPU
ResetCPU1Usage=1
CPUMinTemp1=>
ResetCPU1MinTemp1=1
ResetCPU1MaxTemp2=1
CPUFanTach1=>
ResetCPUFanTach1Min=1
ResetCPUFanTach1Max=1

;RAM
RAMMin=>
ResetRAMMin=1
ResetRamMax=1

;GPU0
ResetGPU0Usage=1
GPU0MinTemp=>
ResetGPU0MinTemp1=1
ResetGPU0MaxTemp2=1
GPU0MinTach=>
ResetGPU0TachMin=1
ResetGPU0TachMax=1
GPU0MinMem=>
ResetGPU0MinMem=1
ResetGPUMaxMem1=1

;GPU1
ResetGPU1Usage=1
GPU1MinTemp=>
ResetGPU1MinTemp1=1
ResetGPU1MaxTemp2=1
GPU1MinTach=>
ResetGPU1TachMin=1
ResetGPU1TachMax=1
GPU1MinMem=>
ResetGPU1MinMem=1
ResetGPUMaxMem1=1